// <auto-generated />
using System;
using DownloadManager.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DownloadManager.Core.Migrations
{
    [DbContext(typeof(DownloadManagerDbContext))]
    [Migration("20251022145040_AddFileScanCache")]
    partial class AddFileScanCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DownloadManager.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#ef4444",
                            FileExtensions = "[\"mp4\",\"avi\",\"mkv\",\"mov\",\"wmv\",\"flv\",\"webm\"]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Videos",
                            Icon = "video",
                            IsSystem = true,
                            MimeTypes = "[\"video/mp4\",\"video/x-msvideo\",\"video/x-matroska\"]",
                            Name = "Video"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3b82f6",
                            FileExtensions = "[\"pdf\",\"doc\",\"docx\",\"xls\",\"xlsx\",\"ppt\",\"pptx\",\"txt\"]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Documents",
                            Icon = "document",
                            IsSystem = true,
                            MimeTypes = "[\"application/pdf\",\"application/msword\",\"application/vnd.openxmlformats-officedocument.wordprocessingml.document\"]",
                            Name = "Documents"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#8b5cf6",
                            FileExtensions = "[\"exe\",\"msi\",\"dmg\",\"pkg\",\"deb\",\"rpm\"]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Software",
                            Icon = "software",
                            IsSystem = true,
                            MimeTypes = "[\"application/x-msdownload\",\"application/x-msi\"]",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#f59e0b",
                            FileExtensions = "[\"zip\",\"rar\",\"7z\",\"tar\",\"gz\",\"bz2\"]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Archives",
                            Icon = "archive",
                            IsSystem = true,
                            MimeTypes = "[\"application/zip\",\"application/x-rar-compressed\",\"application/x-7z-compressed\"]",
                            Name = "Archives"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#10b981",
                            FileExtensions = "[\"mp3\",\"wav\",\"flac\",\"aac\",\"ogg\",\"m4a\"]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Music",
                            Icon = "music",
                            IsSystem = true,
                            MimeTypes = "[\"audio/mpeg\",\"audio/wav\",\"audio/flac\"]",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ec4899",
                            FileExtensions = "[\"jpg\",\"jpeg\",\"png\",\"gif\",\"bmp\",\"svg\",\"webp\"]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Images",
                            Icon = "image",
                            IsSystem = true,
                            MimeTypes = "[\"image/jpeg\",\"image/png\",\"image/gif\"]",
                            Name = "Images"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#6b7280",
                            FileExtensions = "[]",
                            FolderPath = "C:\\Users\\meade\\Downloads\\Other",
                            Icon = "file",
                            IsSystem = true,
                            MimeTypes = "[]",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.DownloadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventData")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.ToTable("DownloadHistory");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.DownloadSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedMirrorId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndByte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MirrorUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartByte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMirrorId");

                    b.HasIndex("DownloadId");

                    b.HasIndex("DownloadId", "SegmentIndex")
                        .IsUnique();

                    b.ToTable("DownloadSegments");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.DownloadTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChecksumAlgorithm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referrer")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SpeedLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncToken")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.FileScanCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSafe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveDetections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScanResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScans")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FileHash");

                    b.ToTable("FileScanCaches");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.MirrorFailoverEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NewMirrorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewMirrorUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OldMirrorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OldMirrorUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NewMirrorId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("OldMirrorId");

                    b.HasIndex("SegmentId");

                    b.ToTable("MirrorFailoverEvents");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.MirrorUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.HasIndex("DownloadId", "Priority");

                    b.ToTable("MirrorUrls");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.QuarantinedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuarantinePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QuarantinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanResult")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.ToTable("QuarantinedFiles");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.ScheduledDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceData")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrencePattern")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.HasIndex("NextRun", "IsActive");

                    b.ToTable("ScheduledDownloads");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.DownloadHistory", b =>
                {
                    b.HasOne("DownloadManager.Shared.Models.DownloadTask", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Download");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.DownloadSegment", b =>
                {
                    b.HasOne("DownloadManager.Shared.Models.MirrorUrl", "AssignedMirror")
                        .WithMany()
                        .HasForeignKey("AssignedMirrorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DownloadManager.Shared.Models.DownloadTask", "Download")
                        .WithMany("Segments")
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMirror");

                    b.Navigation("Download");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.MirrorFailoverEvent", b =>
                {
                    b.HasOne("DownloadManager.Shared.Models.MirrorUrl", "NewMirror")
                        .WithMany()
                        .HasForeignKey("NewMirrorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DownloadManager.Shared.Models.MirrorUrl", "OldMirror")
                        .WithMany()
                        .HasForeignKey("OldMirrorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DownloadManager.Shared.Models.DownloadSegment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewMirror");

                    b.Navigation("OldMirror");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.MirrorUrl", b =>
                {
                    b.HasOne("DownloadManager.Shared.Models.DownloadTask", "Download")
                        .WithMany("MirrorUrls")
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Download");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.QuarantinedFile", b =>
                {
                    b.HasOne("DownloadManager.Shared.Models.DownloadTask", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Download");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.ScheduledDownload", b =>
                {
                    b.HasOne("DownloadManager.Shared.Models.DownloadTask", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Download");
                });

            modelBuilder.Entity("DownloadManager.Shared.Models.DownloadTask", b =>
                {
                    b.Navigation("MirrorUrls");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
